apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: web-container
      image: dodiliz/web-image-user5:latest
      readinessProbe:
        httpGet:
          path: /
          port: 80
      livenessProbe:
        httpGet:
          path: /
          port: 80
    - name: slow-app-container
      image: dodiliz/slow-app-image-user5:latest
