apiVersion: v1
kind: Pod
metadata:
  name: mi-pod-configmap
spec:
  containers:
  - name: mi-contenedor
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: mi-configmap
          key: username
    - name: PASSWORD
      valueFrom:
        configMapKeyRef:
          name: mi-configmap
          key: password
